### ISSUE TITLE
Hi i'm having issues on installing this to arch linux.

### ISSUE THREAD

**Issue by Robyn12** [danielecook/seq-kit#45]
I'd like to install this on arch, but after installing nim and libraries through nimble, it says
"error murmur3.c not found"

**Comment by danielecook** [comment]
Hi - yeah this has been kind of an annoying problem I haven't quite figured out to solve.

You can try it again with the latest master branch OR you can download a pre-built Linux binary from a. recent successful run and see if that works.

For example:

https://github.com/danielecook/seq-collection/actions/runs/94043575

Then do `chmod +x sc_ubuntu-16.04` and see if it works. Let me know if it does not!

Also it would be helpful to know what tool you are interested in and if yo have any feedback.

Thanks!

**Comment by Robyn12** [comment]
I got this response, so it does not work

$./sc_ubuntu-16.04
could not load: libhts.so
compile with -d:nimDebugD1Open for more information

su 10. toukok. 2020 klo 20.17 Daniel E Cook (notifications@github.com)
kirjoitti:

**Comment by Robyn12** [comment]
I'm intrested in vcard to json because I use python to send text messages,
so it's easy to use my phones contacts when using sms on computer

su 10. toukok. 2020 klo 20.43 Joel Ruhanen (ruhanen.joel@gmail.com)
kirjoitti:

**Comment by danielecook** [comment]
Hi - VCF stands for Variant call format.

This is a set of tools related to genetic analysis.

**Comment by Robyn12** [comment]
Yes but I saw this was used on the converting process

su 10. toukok. 2020 klo 21.35 Daniel E Cook (notifications@github.com)
kirjoitti:

**Comment by danielecook** [comment]
The VCF format here is not the same as VCard. One holds genetic variation data and the other holds contact information. This set of utilities operates on the former.
